# Generated by Django 4.1 on 2022-09-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_contact_message_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='QueryType',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message_category',
            new_name='query_type',
        ),
    ]
